/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'rkaneko' at '17/02/19 1:52' with Gradle 2.14
 *
 * @author rkaneko, @date 17/02/19 1:52
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
